### ISSUE TITLE
[Bug]: issue hiding windows that show a buffer shown by another window

### ISSUE THREAD

**Issue by xeluxee** [MunifTanjim/nui.nvim#190]
When I open a window displaying a buffer that already exists (#88) everything works fine. But when `window:hide()` method is called all the windows containing that buffer are closed, and not only the current one.

### Steps to reproduce
1. Run the following code
``` lua
local nui_popup = require("nui.popup")

local popup1 = nui_popup({
	relative = "editor",
	enter = true,
	focusable = true,
	border = {
		style = "rounded",
	},
	position = {
		col = "20%",
		row = "50%",
	},
	size = {
		width = "20%",
		height = "20%",
	},
})
popup1:mount()
popup1:map("n", "q", function()
	popup1:unmount()
end, { noremap = true })
vim.api.nvim_buf_set_lines(popup1.bufnr, 0, 1, false, { "Popup 1" })

local popup2 = nui_popup({
	relative = "editor",
	enter = false,
	focusable = true,
	border = {
		style = "rounded",
	},
	position = {
		col = "50%",
		row = "50%",
	},
	size = {
		width = "20%",
		height = "20%",
	},
})
popup2:mount()
popup2:map("n", "q", function()
	popup2:unmount()
end, { noremap = true })
vim.api.nvim_buf_set_lines(popup2.bufnr, 0, 1, false, { "Popup 2" })

local popup3 = nui_popup({
	bufnr = popup2.bufnr,
	relative = "editor",
	enter = true,
	focusable = true,
	border = {
		style = "rounded",
	},
	position = {
		col = "80%",
		row = "50%",
	},
	size = {
		width = "20%",
		height = "20%",
	},
})
popup3:map("n", "q", function()
	popup3:hide()
end, { noremap = true })

local is_popup3_mounted = false
popup1:map("n", "e", function()
	if not is_popup3_mounted then
		popup3:mount()
		is_popup3_mounted = true
	else
		popup3:show()
	end
end, { noremap = true })
```
2. Press `e` (with cursor focused on popup 1) to open popup 3
3. Press `q` (with cursor focused on popup 3) to hide popup 3
4. Popups 2 and 3 will be hidden, while **only** popup 3 should be closed
5. Focus on popup 1 and press `e` to re-open popup 3
6. You'll get the following error:
```
E5108: Error executing lua: ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: Vim(append):Error executing lua callback: ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:188: invalid augroup: nui_5_hide
stack traceback:
    [C]: in function 'create'
    ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:188: in function <...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:186>
    [C]: in function 'nvim_open_win'
    ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: in function '_open_window'
    ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:237: in function 'show'
    nui_test.lua:74: in function <nui_test.lua:69>
stack traceback:
    [C]: in function 'nvim_open_win'
    ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: in function '_open_window'
    ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:237: in function 'show'
    nui_test.lua:74: in function <nui_test.lua:69>
```

Since I'm experiencing this new issue for less than a month I think it can be caused by recent updates.
Related issue: https://github.com/xeluxee/competitest.nvim/issues/14

**Comment by MunifTanjim** [comment]
@xeluxee 
Thanks so much for the example code 🙌🏼 That made the debugging process so much easier.
This should be fixed now.

**Comment by MunifTanjim** [comment]
btw, fyi, when both the popups are using the same buffer and you do

```lua
popup2:map("n", "q", function()
	popup2:unmount()
end, { noremap = true })
```

then do

```lua
popup3:map("n", "q", function()
	popup3:hide()
end, { noremap = true })
```

It replaces the previous keymap, because keymaps are made against buffer in Neovim. So mapping the same key twice overwrites the previous one. @xeluxee

**Comment by xeluxee** [comment]
Thanks @MunifTanjim for being so fast fixing this issue!

But there's still an issue affecting my plugin, because the same windows are hidden and shown many times. When all windows are hidden and then re-opened, an error occurs, making impossible to open the next popup and making the others unreactive.

### Steps to reproduce
1. Run the following code
``` lua
local nui_popup = require("nui.popup")

local popup_settings = {
	relative = "editor",
	enter = true,
	focusable = true,
	border = {
		style = "rounded",
	},
	position = {
		col = "20%",
		row = "50%",
	},
	size = {
		width = "20%",
		height = "20%",
	},
}

local popup1 = nui_popup(popup_settings)
popup1:mount()
vim.api.nvim_buf_set_lines(popup1.bufnr, 0, 1, false, { "Popup 1" })



popup_settings.position.col = "50%"
local popup2 = nui_popup(vim.deepcopy(popup_settings))
popup2:mount()
vim.api.nvim_buf_set_lines(popup2.bufnr, 0, 1, false, { "Popup 2" })



popup_settings.position.col = "80%"
popup_settings.bufnr = popup2.bufnr
local popup3 = nui_popup(vim.deepcopy(popup_settings))
popup3:mount()

vim.defer_fn(function()
	popup3:hide()
	popup2:hide()
	popup1:hide()
	vim.defer_fn(function()
		popup1:show()
		popup2:show()
		popup3:show()
	end, 1000)
end, 1000)
```
2. After 2 seconds this error occurs, and popup 3 cannot be shown
```
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: Vim(append):Error executing lua callback: ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:194: invalid augroup: nui_3_hide
stack traceback:
        [C]: in function 'create'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:194: in function <...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:186>
        [C]: in function 'nvim_open_win'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: in function '_open_window'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:244: in function 'show'
        nui_test.lua:52: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_open_win'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:138: in function '_open_window'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:244: in function 'show'
        nui_test.lua:52: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by xeluxee** [comment]
Thank you for maintaining this plugin! Now everything is working fine for popups.

But I've just noticed that this issue is affecting some splits :disappointed:
I'm experiencing that while using my plugin: when I close a popup, the split sharing the same buffer is closed, but not always.
At the moment I'm not able to reproduce this behaviour with a sample code, I'll try to provide a working example asap.

**Comment by MunifTanjim** [comment]
Let's open a new issue for that.

> when I close a popup

How is it closed? Using some nui method? Using `:bdelete` or `:quit` command? Or some other way?

**Comment by xeluxee** [comment]
> How is it closed?

`popup:hide()`

> Also how are you setting existing buffer to split?

It's the opposite: I'm opening a popup showing a buffer from an already existing split

**Comment by MunifTanjim** [comment]
> I'm opening a popup showing a buffer from an already existing split

Is that split managed my nui? Or a normal vim split?
